python model/main.py --split_index 0 --n_epochs 200 --batch_size 40 --video_type 'TVSum'
python model/main.py --split_index 1 --n_epochs 200 --batch_size 40 --video_type 'TVSum'
python model/main.py --split_index 2 --n_epochs 200 --batch_size 40 --video_type 'TVSum'
python model/main.py --split_index 3 --n_epochs 200 --batch_size 40 --video_type 'TVSum'
python model/main.py --split_index 4 --n_epochs 200 --batch_size 40 --video_type 'TVSum'
